### ISSUE TITLE
Python code blocks in documentation 

### ISSUE THREAD

**Issue by sophialilleengen** [EXP-code/EXP-docs#14]
Throughout the pages, some code blocks are written as `.. code:: ipython3`  where they don't show up as Python code in the docs (e.g. [here](https://exp-docs.readthedocs.io/en/latest/topics/make-movies.html)). With `.. code-block:: python`  it works and looks nice (e.g. [here](https://exp-docs.readthedocs.io/en/latest/topics/visualizing-bases.html)). If nobody claims this issue, I will go through the pages and fix these where I find them.

**Comment by The9Cat** [comment]
Thanks Sophia.  I fixed this in a pending PR #12  and merged it.  Please check that it's fixed on your end when you have a chance.

**Comment by sophialilleengen** [comment]
Looks good to me!
